### ISSUE TITLE
DNS-SD advertising of IPP printer is not compatible with iOS

### ISSUE THREAD

**Issue by alexpevzner** [OpenPrinting/ipp-usb#4]
iOS devices doesn't see IPP printer on a network, as advertised by the `ipp-usb`

Moved here from #3

**Comment by scubajeff** [comment]
Confirmed fixed. With `interface = all` in `ipp-usb.conf`, `ipp-usb` can advertise IPP printer to iOS devices and sever print jobs well. With `interface = loopback`, which is the recommended secure way, no one on LAN can see the print queue. `avahi` daemon won't pick up the local print queue, even though it passes the test procedure you designed.

**Comment by alexpevzner** [comment]
Closed - resolved
