### ISSUE TITLE
Wrong paper size advertised for HP LaserJet MFP M28

### ISSUE THREAD

**Issue by alexpevzner** [OpenPrinting/ipp-usb#6]
Advertised paper size is `"<legal-A4"`, must be `"legal-A4"`

Note, this printer reports maximum paper size {215.90 x 296.92}, which is less that Legal, but definitely is not less that A4

**Comment by scubajeff** [comment]
Confirm fixed.

**Comment by alexpevzner** [comment]
Closed - resolved
