### ISSUE TITLE
IPP-USB-like tool on Android

### ISSUE THREAD

**Issue by tangyanli** [OpenPrinting/ipp-usb#67]
Dear Alexander:

Do you know if there is software on Android that provides IPP-USB-like functionality (implementing the IPP-Over-USB protocol)?

**Comment by alexpevzner** [comment]
Hi Tess,

I don't know anything about Android. In theory, two approaches are possible:
* make printing and scanning clients aware about IPP over USB specifics (i.e., they must always terminate HTTP transaction correctly)
* insert a proxy that will take care about correct HTTP transactions termination into the path -- this is `ipp-usb` approach

May be, Android goes the first way

**Comment by tangyanli** [comment]
Got it, thanks for your answer!
