### ISSUE TITLE
This IPP-USB is installed on the client side, right? For developers, is there any code available for the device end, like the printer's code? Is there any open-source code for the printer?

### ISSUE THREAD

**Issue by pz123456789** [OpenPrinting/ipp-usb#82]
This IPP-USB is installed on the client side, right? For developers, is there any code available for the device end, like the printer's code? Is there any open-source code for the printer? How is the print end implemented to communicate with the client via USB using IPP?

**Comment by alexpevzner** [comment]
Yes, ipp-usb is the client-side software.

At the printer side, IPP must be somehow implemented (which was initially defined as a network protocol and uses HTTP as a transport), plus some kind of reverse proxy needs to be implemented, which will provide traffic funnelling between USB and IPP server.

About open-source printer firmware, I'm not aware if it exists. Please note, writing production-quality IPP stack from the ground up is a really big task.

**Comment by alexpevzner** [comment]
What operating system runs **inside** the device?

**Comment by pz123456789** [comment]
linux Embedded system

**Comment by pz123456789** [comment]
Teacher, can you add a wechat contact? I am a beginner in this field.

**Comment by alexpevzner** [comment]
> linux Embedded system

https://www.kernel.org/doc/html/v4.15/driver-api/usb/gadget.html

> Teacher, can you add a wechat contact? I am a beginner in this field.

I don't have wechat. Only e-mail and Telegram.

**Comment by pz123456789** [comment]
Could you please share your email address? Thank you, teacher.

**Comment by alexpevzner** [comment]
pzz@apevzner.com

It is listed at the every `ipp-usb` source file :)

**Comment by tillkamppeter** [comment]
There is a free implementation of the server sside of IPP-over-USB, in PAPPL from Michael Sweet. PAPPL, rge Printer APPlication Library is not only there to make Printer Applications, emulations of driverless IPP printers as a replacement for printer drivers, but it also serves as printer firmware, to make the printer driverless. And for USB it has trhe so-called "Gadget" mode.

See http://github.com/michaelrsweet/pappl
